spring:
  jackson:
    time-zone: UTC
  application:
    name: dscatalog
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false
dscatalog:
  security:
    client-id: ${CLIENT_ID:myclientid}
    client-secret: ${CLIENT_SECRET:myclientsecret}
    jwt:
      duration: ${JWT_DURATION:86400}
    cors:
      origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}