spring:
  jackson:
    time-zone: UTC
  application:
    name: dscatalog
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false
    #phmw wrcs khme qsks
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:test@gmail.com}
    password: ${EMAIL_PASSWORD:123456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
dscatalog:
  email:
    password-recover:
      uri: ${PASSWORD_RECOVER_URI:http://localhost:5173/recover-passwords}
      expiration-token-seconds: ${PASSWORD_RECOVER_EXPIRATION_TOKEN_SECONDS:1800}
  security:
    client-id: ${CLIENT_ID:myclientid}
    client-secret: ${CLIENT_SECRET:myclientsecret}
    jwt:
      duration: ${JWT_DURATION:86400}
    cors:
      origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}